server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinems
    username: xon9798
    password: 9798
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
